
name:  Deops GitHub Actions
on:
  push:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Deploy on Excloud
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: 210.79.129.187
              key: ${{secrets.PRIVATE_KEY}}
              script: |
                export NUM_DIR="$HOME/.nvm"
                [ -s "$NUM_DIR/nvm.sh"] && \. "$NVM_DIR/nvm.sh"s
                cd /home/ubuntu/deops
                git pull
                npm install
                pm2 restart 1
